export class DataSync {
  constructor(containerId) {
    this.container = document.getElementById(containerId);
    if (!this.container) return;
    this.init();
  }

  async init() {
    this.container.innerHTML = `<div class="empty-state"><p>Loading sync data...</p></div>`;
    try {
      // Fetch version data generated by sync.js
      const response = await fetch(import.meta.env.BASE_URL + 'data/version.json');
      if (!response.ok) throw new Error('Network response was not ok');
      const data = await response.json();
      this.render(data);
    } catch (error) {
      console.error('Failed to load version data:', error);
      this.container.innerHTML = `
        <div class="empty-state">
          <p class="text-apb-red">Failed to load sync data.</p>
          <p>Please ensure the GitHub Actions sync script has run successfully.</p>
        </div>
      `;
    }
  }

  render(data) {
    const formattedDate = new Date(data.lastSynced).toLocaleString();
    
    // We know these are generated by our sync script
    const files = [
      'WeaponItemTypes.ger',
      'VehicleItemTypes.ger',
      'InventoryItemTypes.ger',
      'ModifierItemTypes.ger',
      'PlayerRoles.ger',
      'TaskObjectives.ger'
    ];

    let filesHtml = files.map(file => `
      <div class="output-row">
        <span class="label">Generated File</span>
        <code>/data/${file}</code>
        <a href="${import.meta.env.BASE_URL}data/${file}" target="_blank" class="btn btn-sm">View Raw</a>
      </div>
    `).join('');

    this.container.innerHTML = `
      <div class="converter-card" style="margin-bottom: 2rem;">
        <h3>Database Status</h3>
        <div class="output-row">
          <span class="label">Live APBDb Version</span>
          <code class="success-text">${data.version}</code>
        </div>
        <div class="output-row">
          <span class="label">Last Synced On</span>
          <code>${formattedDate}</code>
        </div>
        <div class="output-row">
          <span class="label">Data Source</span>
          <code>${data.source}</code>
        </div>
      </div>
      
      <div class="converter-card">
        <h3>Generated Files</h3>
        <p class="panel-desc" style="margin-bottom: 1rem;">These localization files were automatically rebuilt during the last sync.</p>
        ${filesHtml}
      </div>
    `;
  }
}
