name: APBDb Sync
on:
  schedule:
    - cron: '0 20 * * 3'
  workflow_dispatch:
jobs:
  sync-data:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    permissions:
      contents: write
      pages: write
      id-token: write
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
      - name: Install dependencies
        run: npm ci
      - name: Run Sync Script
        run: node scripts/sync.js
        
      - name: Commit Synced Data
        run: |
          git config --global user.name "Esurient (Automation)"
          git config --global user.email "138257050+xEsurient@users.noreply.github.com"
          git add public/data/
          git commit -m "🤓 DB Sync" || echo "No changes to commit"
          git push
          
      - name: Build Vite App
        run: npm run build
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
